version: "3.9"
services:
  worker:
    build: .
    environment:
      HNDLR: 
      SESSION: $SESSION
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      SUDO_USERS: $SUDO_USERS  # defaults to None
      CHANNEL: $CHANNEL  # defaults to None
      OWNER_NAME: $OWNER_NAME
